apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ma-kuber-ingress
  annotations:
    spec.ingressClassName: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/vasiliy/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: ma-kuber-service
              port:
                number: 80
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: ma-kuber-service
              port:
                number: 80
